name: completer_ex
version: 1.0.0
homepage: https://github.com/bsutton/completer_ex
description: A wrapper for Completer which logs when the completer doesn't complete in a timel manner.
environment: 
  sdk: '>=2.8.1 <3.0.0'
dependencies: 
  simple_logger: ^1.7.0
  stacktrace_impl: ^1.0.0
dev_dependencies: 
  pedantic: ^1.9.0
  test: 1.6.3
